### ISSUE TITLE
Few notes

### ISSUE THREAD

**Issue by bi6o** [kaisbitar/quran_parser_test#1]
First of all, great work! The code is following a good number of practices for good code.

A few notes come to mind:

- I noticed that you are doing some logic in your `index.js` before sending the data to your `full_sura_pro.php` such as `santizeComma`, `calculateNumberOfVerses`, `calculateNumberOfWords`. It is good practice to keep all the logic in the backend, so that the frontend would be faster (remember, javascript runs on browser and PHP runs on the server)

- the name of the file `full_sura_pro.php` should follow the CamelCase standard that you're following in the `_classes` folder, or vise versa. This would be good to keep one type of naming to follow throughout the project

- The data you provided in the القران كاملا بدون تشكيل is of type `html`. The data in the root directory `*.txt` is perfect, since it's easier to treat it as a string (text) than to extract from `html` files.

- Did you consider providing a `README.dm` file explaining how to run the app on the local machine? Such a document would give great help for anyone who wants to participate in the project, to get up-and-running

Thanks again!

**Comment by kaisbitar** [comment]
Great. Thanks, let's discuss
